import React from "react";
import Discount from "../Common/Discount";
import Title from "../Common/Title";

const PrivacyPolicy = () => {
    document.title = "PRIVACY POLICY － TEAFLOW";
    return (
        <div>
            <Title text={"returns and exchanges"} />
            <div className="px-5 sm:pl-[14.44vw] sm:pr-[32vw] mx-auto font-GolosRegular">
                <div className="mt-[7vw]">
                    <p className="text-lg sm:text-[1.2vw] leading-[130%] sm:leading-[2.3vw] mb-16 sm:mb-[4vw]">
                        Effective date: January 1, 2023 P.B CORP ("us", "we", or
                        "our") operates the www.tea-flow.com website (the
                        "Service"). This page informs you of our policies
                        regarding the collection, use, and disclosure of
                        personal data when you use our Service and the choices
                        you have associated with that data. We use your data to
                        provide and improve the Service. By using the Service,
                        you agree to the collection and use of information in
                        accordance with this policy. Unless otherwise defined in
                        this Privacy Policy, terms used in this Privacy Policy
                        have the same meanings as in our Terms and Conditions,
                        accessible from www.tea-flow.com
                    </p>
                </div>
                <div className="">
                    <h6 className="text-[12px] sm:text-[0.7vw] leading-[130%] sm:leading-[2.1vw] uppercase font-medium mt-5">
                        Definitions
                    </h6>
                    <h4 className="text-lg sm:text-[1.2vw] leading-[130%] sm:leading-[2.3vw] font-GolosBold my-5 sm:mb-[0.2vw] sm:mt-[1vw]">
                        Service
                    </h4>
                    <p className="text-lg sm:text-[1.2vw] leading-[130%] sm:leading-[2.3vw]">
                        Service is the www.tea-flow.com website operated by P.B
                        corp
                    </p>
                    <h4 className="text-lg sm:text-[1.2vw] leading-[130%] sm:leading-[2.3vw] font-GolosBold my-5 sm:mb-[0.2vw] sm:mt-[1vw]">
                        Personal Data
                    </h4>
                    <p className="text-lg sm:text-[1.2vw] leading-[130%] sm:leading-[2.3vw]">
                        Personal Data means data about a living individual who
                        can be identified from that data (or from those and
                        other information either in our possession or likely to
                        come into our possession).
                    </p>
                    <h4 className="text-lg sm:text-[1.2vw] leading-[130%] sm:leading-[2.3vw] font-GolosBold my-5 sm:mb-[0.2vw] sm:mt-[1vw]">
                        Usage Data
                    </h4>
                    <p className="text-lg sm:text-[1.2vw] leading-[130%] sm:leading-[2.3vw]">
                        Usage Data is data collected automatically either
                        generated by the use of the Service or from the Service
                        infrastructure itself (for example, the duration of a
                        page visit).
                    </p>
                    <h4 className="text-lg sm:text-[1.2vw] leading-[130%] sm:leading-[2.3vw] font-GolosBold my-5 sm:mb-[0.2vw] sm:mt-[1vw]">
                        Cookies
                    </h4>
                    <p className="text-lg sm:text-[1.2vw] leading-[130%] sm:leading-[2.3vw]">
                        Cookies are small pieces of data stored on your device
                        (computer or mobile device).
                    </p>
                    <h4 className="text-lg sm:text-[1.2vw] leading-[130%] sm:leading-[2.3vw] font-GolosBold my-5 sm:mb-[0.2vw] sm:mt-[1vw]">
                        Data Controller
                    </h4>
                    <p className="text-lg sm:text-[1.2vw] leading-[130%] sm:leading-[2.3vw]">
                        Data Controller means the natural or legal person who
                        (either alone or jointly or in common with other
                        persons) determines the purposes for which and the
                        manner in which any personal information is, or are to
                        be, processed. For the purpose of this Privacy Policy,
                        we are a Data Controller of your Personal Data.
                    </p>
                    <h4 className="text-lg sm:text-[1.2vw] leading-[130%] sm:leading-[2.3vw] font-GolosBold my-5 sm:mb-[0.2vw] sm:mt-[1vw]">
                        Data Processors (or Service Providers)
                    </h4>
                    <p className="text-lg sm:text-[1.2vw] leading-[130%] sm:leading-[2.3vw]">
                        Data Processor (or Service Provider) means any natural
                        or legal person who processes the data on behalf of the
                        Data Controller. We may use the services of various
                        Service Providers in order to process your data more
                        effectively.
                    </p>
                    <h4 className="text-lg sm:text-[1.2vw] leading-[130%] sm:leading-[2.3vw] font-GolosBold my-5 sm:mb-[0.2vw] sm:mt-[1vw]">
                        Data Subject (or User)
                    </h4>
                    <p className="text-lg sm:text-[1.2vw] leading-[130%] sm:leading-[2.3vw]">
                        Data Subject is any living individual who is using our
                        Service and is the subject of
                    </p>
                </div>
                <div className="">
                    <h4 className="text-lg sm:text-[1.2vw] leading-[130%] sm:leading-[2.3vw] font-GolosBold my-5 sm:mb-[0.2vw] sm:mt-[1vw]">
                        Personal Data.
                    </h4>
                    <ol
                        className="text-lg sm:text-[1.2vw] leading-[130%] sm:leading-[2.3vw] pl-0 sm:pl-[1.1vw]"
                    >
                        <li >
                            Your Data Protection Rights Under the California
                            Consumer Privacy Act (CCPA) If you are a California
                            Consumer please see our CCPA Privacy Appendix for
                            details and information. Also, please note that we
                            do not sell personal data.{" "}
                            <a href="">Link to CCPA Privacy Appendix.</a>
                            Information Collection and Use <br />
                            We collect several different types of information
                            for various purposes to provide <br /> and improve
                            our Service to you. <br />
                            Types of Data Collected <br />
                            <span className="block font-GolosBold my-5 sm:my-[0.5vw]">
                                Personal Data
                            </span>
                            While using our Service, we may ask you to provide
                            us with certain personally identifiable information
                            that can be used to contact or identify you
                            ("Personal Data"). Personally identifiable
                            information may include, but is not limited to:
                        </li>
                        <li className="mt-3 sm:mt-[0.5vw]">Email address</li>
                        <li className="mt-3 sm:mt-[0.5vw]">
                            First name and last name
                        </li>
                        <li className="mt-3 sm:mt-[0.5vw]">Phone number</li>
                        <li className="mt-3 sm:mt-[0.5vw]">
                            Address, State, Province, ZIP/Postal code, City
                        </li>
                        <li className="mt-3 sm:mt-[0.5vw]">Cookies and Usage Data</li>
                    </ol>
                </div>
                <div className="mt-14 sm:mt-[4vw]">
                    <h4 className="text-lg sm:text-[1.2vw] leading-[130%] sm:leading-[2.3vw] font-GolosBold my-5 sm:mb-[0.2vw] sm:mt-[1vw]">
                        Usage Data
                    </h4>
                    <p className="text-lg sm:text-[1.2vw] leading-[130%] sm:leading-[2.3vw]">
                        We may also collect information on how the Service is
                        accessed and used ("Usage Data"). This Usage Data may
                        include information such as your computer's Internet
                        Protocol address (e.g. IP address), browser type,
                        browser version, the pages of our Service that you
                        visit, the time and date of your visit, the time spent
                        on those pages, unique device identifiers and other
                        diagnostic data.
                    </p>
                    <h4 className="text-lg sm:text-[1.2vw] leading-[130%] sm:leading-[2.3vw] font-GolosBold my-5 sm:mb-[0.2vw] sm:mt-[1vw]">
                        Tracking Cookies Data
                    </h4>
                    <p className="text-lg sm:text-[1.2vw] leading-[130%] sm:leading-[2.3vw]">
                        We use cookies and similar tracking technologies to
                        track the activity on our Service and hold certain
                        information. Cookies are files with a small amount of
                        data which may include an anonymous unique identifier.
                        Cookies are sent to your browser from a website and
                        stored on your device. Tracking technologies also used
                        are beacons, tags, and scripts to collect and track
                        information and to improve and analyze our Service. You
                        can instruct your browser to refuse all cookies or to
                        indicate when a cookie is being sent. However, if you do
                        not accept cookies, you may not be able to use some
                        portions of our Service.
                    </p>
                    <h4 className="text-lg sm:text-[1.2vw] leading-[130%] sm:leading-[2.3vw] font-GolosBold my-5 sm:mb-[0.2vw] sm:mt-[1vw]">
                        Examples of Cookies we use:
                    </h4>
                </div>
                {/*  */}
                <div className="mt-8 sm:mt-[5vw]">
                    <ol
                        className="text-lg sm:text-[1.2vw] leading-[150%] sm:leading-[2.3vw] pl-0 sm:pl-[1.1vw]"
                    >
                        <li className="mt-3 sm:mt-[0.5vw]">
                            <span className="font-medium inline">
                                Session Cookies.
                            </span>{" "}
                            We use Session Cookies to operate our Service.
                        </li>
                        <li className="mt-3 sm:mt-[0.5vw]">
                            <span className="font-medium inline">
                                Preference Cookies.
                            </span>
                            We use Preference Cookies to remember your
                            preferences and various settings.
                        </li>
                        <li className="mt-3 sm:mt-[0.5vw]">
                            <span className="font-medium inline">
                                Security Cookies.
                            </span>{" "}
                            We use Security Cookies for security purposes.
                        </li>
                    </ol>
                </div>
                <div className="mt-8 sm:mt-[5vw]">
                    <h5 className="text-lg sm:text-[1.2vw] leading-[130%] sm:leading-[2.3vw] mb-3 sm:mb-[0.5vw]">
                        Use of Data
                    </h5>
                    <h5 className="text-lg sm:text-[1.2vw] leading-[130%] sm:leading-[2.3vw] mb-5 sm:mb-[1.1vw]">
                        P.B CORP uses the collected data for various purposes:
                    </h5>
                    <div className="pl-0 sm:pl-[1.1vw]">
                        <ol

                            className="text-lg sm:text-[1.2vw] leading-[130%] sm:leading-[2.3vw] pl-[1.1vw] flex flex-col gap-2 sm:gap-[1.1vw]"
                        >
                            <li className="mb-3 sm:mb-[0.5vw]">To provide and maintain our Service</li>
                            <li className="mb-3 sm:mb-[0.5vw]">To notify you about changes to our Service</li>
                            <li className="mb-3 sm:mb-[0.5vw]">
                                To allow you to participate in interactive
                                features of our Service when you choose to do so
                            </li>
                            <li className="mb-3 sm:mb-[0.5vw]">To provide customer support</li>
                            <li className="mb-3 sm:mb-[0.5vw]">
                                To gather analysis or valuable information so
                                that we can improve our Service
                            </li>
                            <li className="mb-3 sm:mb-[0.5vw]">To monitor the usage of our Service</li>
                            <li className="mb-3 sm:mb-[0.5vw]">
                                To detect, prevent and address technical issues{" "}
                                <br />{" "}
                                <span>
                                    Legal Basis for Processing Personal Data
                                    Under General Data Protection Regulation
                                    (GDPR) <br />
                                    If you are from the European Economic Area
                                    (EEA), P.B CORP legal basis for collecting
                                    and using the personal information described
                                    in this Privacy Policy depends on the
                                    Personal Data we collect and the specific
                                    context in which we collect it. P.B CORP may
                                    process your Personal Data because:
                                </span>
                            </li>
                            <li>We need to perform a contract with you</li>
                            <li>You have given us permission to do so</li>
                            <li>
                                The processing is in our legitimate interests
                                and it's not overridden by your rights
                            </li>
                            <li>For payment processing purposes</li>
                            <li>
                                To comply with the law <span></span> Retention
                                of Data <br />
                                <span className="block mt-3 sm:mt-[1.1vw]">
                                    P.B CORP will retain your Personal Data only
                                    for as long as is necessary for the purposes
                                    set out in this Privacy Policy. We will
                                    retain and use your Personal Data to the
                                    extent necessary to comply with our legal
                                    obligations (for example, if we are required
                                    to retain your data to comply with
                                    applicable laws), resolve disputes, and
                                    enforce our legal agreements and policies.{" "}
                                    <br />
                                    P.B CORP will also retain Usage Data for
                                    internal analysis purposes. Usage Data is
                                    generally retained for a shorter period of
                                    time, except when this data is used to
                                    strengthen the security or to improve the
                                    functionality of our Service, or we are
                                    legally obligated to retain this data for
                                    longer time periods. <br />
                                    Transfer of Data <br />
                                    Your information, including Personal Data,
                                    may be transferred to -- and maintained on
                                    -- computers located outside of your state,
                                    province, country or other governmental
                                    jurisdiction where the data protection laws
                                    may differ from those from your
                                    jurisdiction. <br />
                                    If you are located outside the United States
                                    and choose to provide information to us,
                                    please note that we transfer the data,
                                    including Personal Data, to the United
                                    States and process it there. <br />
                                    Your consent to this Privacy Policy followed
                                    by your submission of such information
                                    represents your agreement to that transfer.{" "}
                                    <br />
                                    P.B CORP will take all steps reasonably
                                    necessary to ensure that your data is
                                    treated securely and in accordance with this
                                    Privacy Policy and no transfer of your
                                    Personal Data will take place to an
                                    organization or a country unless there are
                                    adequate controls in place including the
                                    security of your data and other personal
                                    information. <br />
                                    Disclosure of Data <br />
                                    Disclosure for Law Enforcement <br />
                                    Under certain circumstances, P.B CORP may be
                                    required to disclose your Personal Data if
                                    required to do so by law or in response to
                                    valid requests by public authorities (e.g. a
                                    court or a government agency). <br />
                                    Legal Requirements <br />
                                    P.B CORP may disclose your Personal Data in
                                    the good faith belief that such action{" "}
                                    <br /> is necessary to:
                                </span>
                            </li>
                            <br />
                            <li>To comply with a legal obligation</li>
                            <li>
                                To protect and defend the rights or property of
                                P.B CORP
                            </li>
                            <li>
                                To prevent or investigate possible wrongdoing in
                                connection with the Service
                            </li>
                            <li>
                                To protect the personal safety of users of the
                                Service or the public
                            </li>
                            <li>To protect against legal liability</li>
                            <li>
                                <span>Security of Data</span>
                                <span className="mt-3 sm:mt-[1.1vw] block">
                                    The security of your data is important to
                                    us, but remember that no method of
                                    transmission over the Internet, or method of
                                    electronic storage is 100% secure. While we
                                    strive to use commercially acceptable means
                                    to protect your Personal Data, we cannot
                                    guarantee its absolute security. <br />
                                    "Do Not Track" Signals <br />
                                    We do not support Do Not Track ("DNT"). Do
                                    Not Track is a preference you can set in
                                    your web browser to inform websites that you
                                    do not want to be tracked. You can enable or
                                    disable Do Not Track by visiting the
                                    Preferences or Settings page of your web
                                    browser. <br />
                                    Your Data Protection Rights Under General
                                    Data Protection Regulation (GDPR) If you are
                                    a resident of the European Economic Area
                                    (EEA), you have certain data protection
                                    rights. P.B CORP aims to take reasonable
                                    steps to allow you to correct, amend,
                                    delete, or limit the use of your Personal
                                    Data. <br />
                                    If you wish to be informed what Personal
                                    Data we hold about you and if you want it to
                                    be removed from our systems, please contact
                                    us. <br />
                                    In certain circumstances, you have the
                                    following data protection rights: <br />
                                </span>
                            </li>
                            <li>
                                <span>
                                    The right to access, update or to delete the
                                    information we have on you.
                                </span>{" "}
                                <div className="mt-3 sm:mt-[1.1vw]">
                                    <div className="">
                                        The right of rectification. You have the
                                        right to have your information rectified
                                        if that information is inaccurate or
                                        incomplete. <br />
                                        The right to object. You have the right
                                        to object to our processing of your
                                        Personal Data. <br />
                                        The right of restriction. You have the
                                        right to request that we restrict the
                                        processing of your personal information.{" "}
                                        <br />
                                        The right to data portability. You have
                                        the right to be provided with a copy of
                                        the information we have on you in a
                                        structured, machine-readable and
                                        commonly used format. <br />
                                        The right to withdraw consent. You also
                                        have the right to withdraw your consent
                                        at any time where P.B CORP relied on
                                        your consent to process your personal
                                        information. <br />
                                    </div>
                                </div>
                            </li>
                            <li>
                                Please note that we may ask you to verify your
                                identity before responding to such requests.{" "}
                                <br />
                                <span className="mt-3 sm:mt-[1.1vw] block">
                                    You have the right to complain to a Data
                                    Protection Authority about our collection
                                    and use of your Personal Data. For more
                                    information, please contact your local data
                                    protection authority in the European
                                    Economic Area (EEA). Service Providers{" "}
                                    <br />
                                    We may employ third party companies and
                                    individuals to facilitate our Service
                                    ("Service Providers"), to provide the
                                    Service on our behalf, to perform
                                    Service-related services or to assist us in
                                    analyzing how our Service is used. <br />
                                    These third parties have access to your
                                    Personal Data only to perform these tasks on
                                    our behalf and are obligated not to disclose
                                    or use it for any other purpose. Analytics{" "}
                                    <br />
                                    We may use third-party Service Providers to
                                    monitor and analyze the use of our Service.{" "}
                                </span>
                            </li>
                            <li>
                                <span className="block text-lg sm:text-[1.2vw] leading-[130%] sm:leading-[2.3vw] font-GolosBold my-5 sm:mb-[0.2vw] sm:mt-[1vw]">
                                    Google Analytics
                                </span>
                                Google Analytics is a web analytics service
                                offered by Google that tracks and reports
                                website traffic. Google uses the data collected
                                to track and monitor the use of our Service.
                                This data is shared with other Google services.
                                Google may use the collected data to
                                contextualize and personalize the ads of its own
                                advertising network. <br />
                                You can opt-out of having made your activity on
                                the Service available to Google Analytics by
                                installing the Google Analytics opt-out browser
                                add-on. The add-on prevents the Google Analytics
                                JavaScript (ga.js, analytics.js, and dc.js) from
                                sharing information with Google Analytics about
                                visits activity. <br />
                                For more information on the privacy practices of
                                Google, please visit the Google Privacy Terms
                                web page:{" "}
                                <a
                                    className="underline text-sm sm:text-[1.2vw] text-blue-700"
                                    href=""
                                >
                                    https://policies.google.com/privacy?hl=en
                                </a>
                            </li>
                            <div className="my-10 sm:my-[4vw]">
                                <li>
                                    <span className="block text-lg sm:text-[1.2vw] leading-[130%] sm:leading-[2.3vw] font-GolosBold my-5 sm:mb-[0.2vw] sm:mt-[1vw]">
                                        RightMessage
                                    </span>
                                    We use RightMessage to recommend products
                                    and product categories on our website, based
                                    on the user's browsing behavior. <br />
                                    For more information on the privacy
                                    practices of RightMessage, please visit the
                                    RightMessage Privacy Terms web page:
                                    <a
                                        className="underline text-sm sm:text-[1.2vw] text-blue-700"
                                        href=""
                                    >
                                        https://rightmessage.com/privacy
                                    </a>
                                </li>
                            </div>
                            <li>
                                <span className="block text-lg sm:text-[1.2vw] leading-[130%] sm:leading-[2.3vw] font-GolosBold my-5 sm:mb-[0.2vw] sm:mt-[1vw]">
                                    Mailchimp.
                                </span>
                                Mailchimp remarketing services are provided by
                                The Rocket Science Group LLC. We use Mailchimp
                                to send promotional emails and recommend
                                products in those emails based on customers
                                purchasing and browsing behavior. <br />
                                For more information on the privacy practices of
                                Mailchimp, please visit the Mailchimp Privacy
                                Terms web page:
                                <a
                                    className="underline text-sm sm:text-[1.2vw] text-blue-700"
                                    href=""
                                >
                                    https://mailchimp.com/legal/privacy/
                                </a>
                            </li>
                            <li>
                                <span className="block text-lg sm:text-[1.2vw] leading-[130%] sm:leading-[2.3vw] font-GolosBold my-5 sm:mb-[0.2vw] sm:mt-[1vw]">
                                    Behavioral Remarketing
                                </span>
                                P.B CORP uses remarketing services to advertise
                                on third party websites to you after you visited
                                our Service. We and our third-party vendors use
                                cookies to inform, optimize and serve ads based
                                on your past visits to our Service.
                            </li>
                            <li>
                                <span className="block text-lg sm:text-[1.2vw] leading-[130%] sm:leading-[2.3vw] font-GolosBold my-5 sm:mb-[0.2vw] sm:mt-[1vw]">
                                    Google AdWords
                                </span>
                                Google AdWords remarketing service is provided
                                by Google Inc. You can opt-out of Google
                                Analytics for Display Advertising and customize
                                the Google Display Network ads by visiting the
                                Google Ads Settings page:
                                <a
                                    className="underline text-sm sm:text-[1.2vw] text-blue-700"
                                    href=""
                                >
                                    http://www.google.com/settings/ads{" "}
                                </a>
                                Google also recommends installing the Google
                                Analytics Opt-out Browser Add-on -
                                <a
                                    className="underline text-sm sm:text-[1.2vw] text-blue-700"
                                    href=""
                                >
                                    https://tools.google.com/dlpage/gaoptout{" "}
                                </a>
                                - for your web browser. Google Analytics Opt-out
                                Browser Add-on provides visitors with the
                                ability to prevent their data from being
                                collected and used by Google Analytics. <br />
                                For more information on the privacy practices of
                                Google, please visit the Google Privacy Terms
                                web page:
                                <a
                                    className="underline text-sm sm:text-[1.2vw] text-blue-700"
                                    href=""
                                >
                                    https://policies.google.com/privacy?hl=en{" "}
                                </a>
                            </li>
                            <li>
                                <span className="block text-lg sm:text-[1.2vw] leading-[130%] sm:leading-[2.3vw] font-GolosBold my-5 sm:mb-[0.2vw] sm:mt-[1vw]">
                                    Payments{" "}
                                </span>
                                We may provide paid products and/or services
                                within the Service. In that case, we use
                                third-party services for payment processing
                                (e.g. payment processors). We will not store or
                                collect your payment card details. That
                                information is provided directly to our
                                third-party payment processors whose use of your
                                personal information is governed by their
                                Privacy Policy. These payment processors adhere
                                to the standards set by PCI-DSS as managed by
                                the PCI Security Standards Council, which is a
                                joint effort of brands like Visa, Mastercard,
                                American Express and Discover. PCI-DSS
                                requirements help ensure the secure handling of
                                payment information. <br />
                            </li>
                            <div className="mt-10 sm:mt-[4vw]">
                                <li>
                                    <span className="block text-lg sm:text-[1.2vw] leading-[130%] sm:leading-[2.3vw] font-GolosBold my-5 sm:mb-[0.2vw] sm:mt-[1vw]">
                                        Links to Other Sites
                                    </span>
                                    Our Service may contain links to other sites
                                    that are not operated by us. If you click on
                                    a third party link, you will be directed to
                                    that third party's site. We strongly advise
                                    you to review the Privacy Policy of every
                                    site you visit. <br />
                                    We have no control over and assume no
                                    responsibility for the content, privacy
                                    policies or practices of any third party
                                    sites or services. <br />
                                    Children's Privacy <br />
                                    Our Service does not address anyone under
                                    the age of 18 ("Children"). <br />
                                    We do not knowingly collect personally
                                    identifiable information from anyone under
                                    the age of 18. If you are a parent or
                                    guardian and you are aware that your child
                                    has provided us with Personal Data, please
                                    contact us. If we become aware that we have
                                    collected Personal Data from children
                                    without verification of parental consent, we
                                    take steps to remove that information from
                                    our servers. <br />
                                    Changes to This Privacy Policy <br />
                                    We may update our Privacy Policy from time
                                    to time. We will notify you of any changes
                                    by posting the new Privacy Policy on this
                                    page. <br />
                                    We will let you know via email and/or a
                                    prominent notice on our Service, prior to
                                    the change becoming effective and update the
                                    "effective date" at the top of this Privacy
                                    Policy. <br />
                                    You are advised to review this Privacy
                                    Policy periodically for any changes. Changes
                                    to this Privacy Policy are effective when
                                    they are posted on this page. <br />
                                    Contact Us <br />
                                    If you have any questions about this Privacy
                                    Policy, please contact us:
                                </li>
                            </div>
                            <li>
                                By email: hello at www.tea-flow.com or use our
                                <a
                                    className="underline text-sm sm:text-[1.2vw] text-blue-700 ml-2"
                                    href=""
                                >
                                    contact form here
                                </a>
                            </li>
                        </ol>
                    </div>
                </div>
                {/*  */}
            </div>
            <div className="mt-[14vw]">
                <Discount />
            </div>
            {/*  */}
        </div>
    );
};

export default PrivacyPolicy;
